#!/bin/sh
set -eu

command -v magick >/dev/null || {
    echo "ImageMagick is required to optimize gallery photos. Install it with: brew install imagemagick" >&2
    exit 1
}

optimize_image() {
    file=$1
    size=$2
    quality=$3
    extension=${file##*.}
    temporary="${file}.optimized.${extension}"

    rm -f "$temporary"
    magick "$file" -resize "${size}x" -quality "$quality" "$temporary"
    mv "$temporary" "$file"
    git add -- "$file"
    echo "optimized $file"
}

staged_files=$(git diff --cached --name-only --diff-filter=ACMR -- 'images/fulls/*' 'images/thumbs/*')

for file in $staged_files; do
    case "$file" in
        images/fulls/*.[Jj][Pp][Gg]|images/fulls/*.[Jj][Pp][Ee][Gg])
            optimize_image "$file" 1024 88
            ;;
        images/thumbs/*.[Jj][Pp][Gg]|images/thumbs/*.[Jj][Pp][Ee][Gg])
            optimize_image "$file" 512 85
            ;;
    esac
done
